[package]
name = "tree-sitter-highlight"
description = "Library for performing syntax highlighting with Tree-sitter"
version = "0.21.0-alpha.1"
authors = [
	"Max Brunsfeld <maxbrunsfeld@gmail.com>",
	"Tim Clem <timothy.clem@gmail.com>",
]
license = "MIT"
readme = "README.md"
edition = "2021"
keywords = ["incremental", "parsing", "syntax", "highlighting"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter"
rust-version.workspace = true

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
tree-sitter = { path = "../lib", version = "0.21.0-alpha.1" }

lazy_static = "1.4.0"
regex = "1.7"
thiserror = "1.0"

